version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: sistergo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    environment:
      - APP_PORT=8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=sistergo
      - JWT_SECRET=verysecret
    ports:
      - "8080:8080"

volumes:
  db_data:
